#!/bin/bash -x
here="$(dirname ${BASH_SOURCE})"
if [ ! -e $here/autoload/plug.vim  ]; then
  curl -fLo $here/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim +PlugInstall +qa
